configVersion = 1.0

[[template]]
key = "dockerfile"
assets = [
    ["default/container/dockerfile", "Dockerfile"]
]

[[template]]
key = "dockerfile-rootless"
assets = [
    ["default/container/dockerfile-rootless", "Dockerfile"]
]

[[template]]
key = "gitignore-java"
assets = [
    ["default/git/java.gitignore", ".gitignore"]
]

[[template]]
key = "gitignore-python"
assets = [
    ["default/git/python.gitignore", ".gitignore"]
]

[[template]]
key = "gitignore-javascript"
assets = [
    ["default/git/javascript.gitignore", ".gitignore"]
]

[[template]]
key = "gitignore-golang"
assets = [
    ["default/git/golang.gitignore", ".gitignore"]
]

[[template]]
key = "jenkins"
assets = [
    ["default/ci/jenkinsfile", "Jenkinsfile"]
]

[[template]]
key = "uml-class"
assets = [
    ["default/plantuml/class.puml", "class.puml"]
]

[[template]]
key = "uml-mindmap"
assets = [
    ["default/plantuml/mindmap.puml", "mindmap.puml"]
]

[[template]]
key = "prettier"
assets = [
    ["default/prettier/prettierignore.ignore", ".prettierignore"],
    ["default/prettier/prettierrc.json", ".prettierrc"]
]

[[template]]
key = "systemd-service"
assets = [
    ["default/systemd/unit.service", "unit.service"]
]

[[template]]
key = "systemd-timer"
assets = [
    ["default/systemd/timer.timer", "timer.timer"]
]

